### ISSUE TITLE
for the location of the fstab information /dev/mmcblk0p2

### ISSUE THREAD

**Issue by kometchtech** [friendlyarm/sd-fuse_s5p6818#4]
/dev/mmcblk0p2 mount for the/etc/fstab file is configured, but it is not what?

```
# UNCONFIGURED FSTAB FOR BASE SYSTEM
/dev/mmcblk0p1  /boot           ext4    defaults          0       2
```

**Comment by friendlyarm** [comment]
/dev/mmcblk0p2 is configured as root device by kernel cmdline (see uboot env - bootargs), and will mounted by initramfs.
It isn't required to add /dev/mmcblk0p2 to /etc/fstab .

**Comment by kometchtech** [comment]
@friendlyarm 

OK

Thanks for the Info!
